---
# install Oracle Java in headless mode
- name: Configure local repository to trust the webupd8 java ppa
  sudo: yes
  apt_repository:
    repo: "ppa:webupd8team/java"
    state: present
    update_cache: yes
    validate_certs: no

- name: Accept Oracle Java license
  sudo: yes
  debconf:
    name: "oracle-java{{ java.version }}-installer"
    question: shared/accepted-oracle-license-v1-1
    value: "true"
    vtype: select

- name: Install Oracle Java
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "oracle-java{{ java.version }}-installer"
    - "oracle-java{{ java.version }}-set-default"
